In [10]:
arr = np.array([1,2,3,4,5]) #Create an array

In [11]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
tuple_container=(1,2,3,4,5)

In [13]:
print(tuple_container)

(1, 2, 3, 4, 5)


In [14]:
#arr_tuple = np.array((1,2,3,4,5))
arr_tuple=np.array(tuple_container)
print(arr_tuple)

[1 2 3 4 5]


In [1]:
import numpy as np #!!!!!!!WRITE THIS FIRST

In [2]:
arr_high_dimension=np.array([1,2,3,4,5],ndmin=5)

print(arr_high_dimension)
print("Number of dimensions:",arr_high_dimension.ndim)

[[[[[1 2 3 4 5]]]]]
Number of dimensions: 5


In [3]:
arr_2d=np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [4]:
print(arr_2d)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [5]:
print(arr_2d.ndim)

2


In [6]:
arr_3d=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])

In [7]:
print(arr_3d)
print(arr_3d.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
3


In [8]:
print(arr[2]+arr[3])

NameError: name 'arr' is not defined

In [ ]:
print('2nd element on 1st row',arr_2d[0,1])

2nd element on 1st row 2


In [ ]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print('1st element on 1st row',arr2[0,0])

1st element on 1st row 1


In [9]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('3rd element on 1st row',arr3[0,1,2])

3rd element on 1st row 6


In [10]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [11]:
arr=np.array([1,2,3,4,5,6,7])

print(arr[4:])
print(arr[:4])

[5 6 7]
[1 2 3 4]


In [12]:
print(arr[-1]) #prints last element

7


In [13]:
print(arr[-3:-1])

[5 6]


In [14]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0:2,2])
print(arr.shape)

[3 7]
(2, 4)


In [15]:
arr_5d=np.array([1,2,3],ndmin=5)
print(arr_5d)
print("Shape:",arr_5d.shape)

[[[[[1 2 3]]]]]
Shape: (1, 1, 1, 1, 3)


In [16]:
arr=np.array([1,2,3]) #iterating arrays
for i in arr:
    print(i)

1
2
3


In [17]:
arr=np.array([[1,2,3],[4,5,6]])
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [18]:
arr=np.array([[1,2,3],[4,5,6]])
for i in arr:
    for j in i:
        print(j)
    

1
2
3
4
5
6


In [19]:
#enumeration

arr=np.array([1,2,3])
for idx,x in np.ndenumerate(arr):
    print(idx[0]+1,x)

1 1
2 2
3 3


In [20]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [21]:
#pandas
import pandas as pd

In [62]:
mydataset={
    'Cars':["BMW","Volvo","Ford"],
    'Passings':[3,7,2]
}

In [63]:
myvar=pd.DataFrame(mydataset)
print(myvar)

    Cars  Passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [64]:
print(mydataset)

{'Cars': ['BMW', 'Volvo', 'Ford'], 'Passings': [3, 7, 2]}


In [65]:
#Series in pandas
data=[1,7,2]
series_data=pd.Series(data)
print(series_data)

0    1
1    7
2    2
dtype: int64


In [66]:
#labels in pandas
#rename column

print(series_data[0])

1


In [67]:
data=[1,7,2]
series_data=pd.Series(data,index=["x","y","z"]) #creating my own label
print(series_data)

x    1
y    7
z    2
dtype: int64


In [68]:
print(series_data["y"])

7


In [69]:
calories={"day1":420,"day2":380,"day3":390}
series_data=pd.Series(calories)
print(series_data)

day1    420
day2    380
day3    390
dtype: int64


In [70]:
series_data=pd.Series(calories,index=["day1","day2"])
print(series_data)

day1    420
day2    380
dtype: int64


In [71]:
#Dataframes for manipulation in table
data={
    "calories":[420,380,390],
    "duration":[50,40,30]
}
pandas_data=pd.DataFrame(data)
print(pandas_data)

   calories  duration
0       420        50
1       380        40
2       390        30


In [72]:
print(pandas_data.loc[0])

calories    420
duration     50
Name: 0, dtype: int64


In [73]:
print(pandas_data.loc[[0,1]]) #printing 1st and 2nd column

   calories  duration
0       420        50
1       380        40


In [74]:
data={
    "calories":[420,390,380],
    "duration":[50,40,90]
}
df=pd.DataFrame(data,index=["day1","day2","day3"]) #Naming with index
print(df)

      calories  duration
day1       420        50
day2       390        40
day3       380        90


In [75]:
#refer to the named index:
print(df.loc["day2"])

calories    390
duration     40
Name: day2, dtype: int64


In [23]:
#Reading CSV files

df=pd.read_csv('./data/data.csv')
print(df)
print(df.to_string())
#print entire dataset
#if you have a large dataframe with many rows pandas will only return the first 5 rows and last 5 rows

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147   

In [79]:
print(pd.options.display.max_rows)

60


In [24]:
#reading json files

df=pd.read_json('./data/data.json')
print(df)
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.5
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147   